# Data Cleaning

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\jluco\Desktop\1_Python\0_Agri-food CO2\Agrofood_co2_emission_wf01.csv")
df

,Area,Continent,Year,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,...,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature Â°C
0,Afghanistan,Asia,1990,14.7237,0.0557,205.6077,686.0000,0.0,11.807483,63.1152,...,319.1763,0.0,0.0,NaN,9655167,2593947,5348387.0,5346409.0,2198.963539,0.536167
1,Afghanistan,Asia,1991,14.7237,0.0557,209.4971,678.1600,0.0,11.712073,61.2125,...,342.3079,0.0,0.0,NaN,10230490,2763167,5372959.0,5372208.0,2323.876629,0.020667
2,Afghanistan,Asia,1992,14.7237,0.0557,196.5341,686.0000,0.0,11.712073,53.3170,...,349.1224,0.0,0.0,NaN,10995568,2985663,6028494.0,6028939.0,2356.304229,-0.259583
3,Afghanistan,Asia,1993,14.7237,0.0557,230.8175,686.0000,0.0,11.712073,54.3617,...,352.2947,0.0,0.0,NaN,11858090,3237009,7003641.0,7000119.0,2368.470529,0.101917
4,Afghanistan,Asia,1994,14.7237,0.0557,242.0494,705.6000,0.0,11.712073,53.9874,...,367.6784,0.0,0.0,NaN,12690115,3482604,7733458.0,7722096.0,2500.768729,0.372250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6875,Zimbabwe,Africa,2016,1190.0089,232.5068,70.9451,7.4088,0.0,75.000000,251.1465,...,282.5994,0.0,0.0,417.3150,10934468,5215894,6796658.0,7656047.0,98491.026350,1.120250
6876,Zimbabwe,Africa,2017,1431.1407,131.1324,108.6262,7.9458,0.0,67.000000,255.7975,...,255.5900,0.0,0.0,398.1644,11201138,5328766,6940631.0,7810471.0,97159.311550,0.046500
6877,Zimbabwe,Africa,2018,1557.5830,221.6222,109.9835,8.1399,0.0,66.000000,327.0897,...,257.2735,0.0,0.0,465.7735,11465748,5447513,7086002.0,7966181.0,97668.308200,0.516333
6878,Zimbabwe,Africa,2019,1591.6049,171.0262,45.4574,7.8322,0.0,73.000000,290.1893,...,267.5224,0.0,0.0,444.2335,11725970,5571525,7231989.0,8122618.0,98988.062800,0.985667
6879,Zimbabwe,Africa,2020,481.9027,48.4197,108.3022,7.9733,0.0,73.000000,238.7639,...,266.7316,0.0,0.0,444.2335,11980005,5700460,7385220.0,8284447.0,96505.221850,0.189000

In [3]:
# Delete duplicate rows. None duplicates found. 
df.drop_duplicates()

,Area,Continent,Year,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,...,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature Â°C
0,Afghanistan,Asia,1990,14.7237,0.0557,205.6077,686.0000,0.0,11.807483,63.1152,...,319.1763,0.0,0.0,NaN,9655167,2593947,5348387.0,5346409.0,2198.963539,0.536167
1,Afghanistan,Asia,1991,14.7237,0.0557,209.4971,678.1600,0.0,11.712073,61.2125,...,342.3079,0.0,0.0,NaN,10230490,2763167,5372959.0,5372208.0,2323.876629,0.020667
2,Afghanistan,Asia,1992,14.7237,0.0557,196.5341,686.0000,0.0,11.712073,53.3170,...,349.1224,0.0,0.0,NaN,10995568,2985663,6028494.0,6028939.0,2356.304229,-0.259583
3,Afghanistan,Asia,1993,14.7237,0.0557,230.8175,686.0000,0.0,11.712073,54.3617,...,352.2947,0.0,0.0,NaN,11858090,3237009,7003641.0,7000119.0,2368.470529,0.101917
4,Afghanistan,Asia,1994,14.7237,0.0557,242.0494,705.6000,0.0,11.712073,53.9874,...,367.6784,0.0,0.0,NaN,12690115,3482604,7733458.0,7722096.0,2500.768729,0.372250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6875,Zimbabwe,Africa,2016,1190.0089,232.5068,70.9451,7.4088,0.0,75.000000,251.1465,...,282.5994,0.0,0.0,417.3150,10934468,5215894,6796658.0,7656047.0,98491.026350,1.120250
6876,Zimbabwe,Africa,2017,1431.1407,131.1324,108.6262,7.9458,0.0,67.000000,255.7975,...,255.5900,0.0,0.0,398.1644,11201138,5328766,6940631.0,7810471.0,97159.311550,0.046500
6877,Zimbabwe,Africa,2018,1557.5830,221.6222,109.9835,8.1399,0.0,66.000000,327.0897,...,257.2735,0.0,0.0,465.7735,11465748,5447513,7086002.0,7966181.0,97668.308200,0.516333
6878,Zimbabwe,Africa,2019,1591.6049,171.0262,45.4574,7.8322,0.0,73.000000,290.1893,...,267.5224,0.0,0.0,444.2335,11725970,5571525,7231989.0,8122618.0,98988.062800,0.985667
6879,Zimbabwe,Africa,2020,481.9027,48.4197,108.3022,7.9733,0.0,73.000000,238.7639,...,266.7316,0.0,0.0,444.2335,11980005,5700460,7385220.0,8284447.0,96505.221850,0.189000

In [4]:
# Values missing per column
df.isnull().sum()

Area                                  0
Continent                             0
Year                                  0
Savanna fires                         0
Forest fires                         62
Crop Residues                      1358
Rice Cultivation                      0
Drained organic soils (CO2)           0
Pesticides Manufacturing              0
Food Transport                        0
Forestland                          493
Net Forest conversion               493
Food Household Consumption          472
Food Retail                           0
On-farm Electricity Use               0
Food Packaging                        0
Agrifood Systems Waste Disposal       0
Food Processing                       0
Fertilizers Manufacturing             0
IPPU                                743
Manure applied to Soils             896
Manure left on Pasture                0
Manure Management                   896
Fires in organic soils                0
Fires in humid tropical forests     124
On-farm energy use                  924
Rural population                      0
Urban population                      0
Total Population - Male               0
Total Population - Female             0
total_emission                        0
Average Temperature Â°C                0
dtype: int64

In [5]:
# Delete columns accounting for missing values higher than 10% of total values.
df01 = df.drop(columns=['Crop Residues','IPPU','Manure applied to Soils','Manure Management','On-farm energy use'])
df01

,Area,Continent,Year,Savanna fires,Forest fires,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,Forestland,...,Fertilizers Manufacturing,Manure left on Pasture,Fires in organic soils,Fires in humid tropical forests,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature Â°C
0,Afghanistan,Asia,1990,14.7237,0.0557,686.0000,0.0,11.807483,63.1152,-2388.8030,...,11.997000,1590.5319,0.0,0.0,9655167,2593947,5348387.0,5346409.0,2198.963539,0.536167
1,Afghanistan,Asia,1991,14.7237,0.0557,678.1600,0.0,11.712073,61.2125,-2388.8030,...,12.853900,1657.2364,0.0,0.0,10230490,2763167,5372959.0,5372208.0,2323.876629,0.020667
2,Afghanistan,Asia,1992,14.7237,0.0557,686.0000,0.0,11.712073,53.3170,-2388.8030,...,13.492900,1653.5068,0.0,0.0,10995568,2985663,6028494.0,6028939.0,2356.304229,-0.259583
3,Afghanistan,Asia,1993,14.7237,0.0557,686.0000,0.0,11.712073,54.3617,-2388.8030,...,14.055900,1642.9623,0.0,0.0,11858090,3237009,7003641.0,7000119.0,2368.470529,0.101917
4,Afghanistan,Asia,1994,14.7237,0.0557,705.6000,0.0,11.712073,53.9874,-2388.8030,...,15.126900,1689.3593,0.0,0.0,12690115,3482604,7733458.0,7722096.0,2500.768729,0.372250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6875,Zimbabwe,Africa,2016,1190.0089,232.5068,7.4088,0.0,75.000000,251.1465,76500.2982,...,2585.080847,2721.1459,0.0,0.0,10934468,5215894,6796658.0,7656047.0,98491.026350,1.120250
6876,Zimbabwe,Africa,2017,1431.1407,131.1324,7.9458,0.0,67.000000,255.7975,76500.2982,...,1227.240253,2744.8763,0.0,0.0,11201138,5328766,6940631.0,7810471.0,97159.311550,0.046500
6877,Zimbabwe,Africa,2018,1557.5830,221.6222,8.1399,0.0,66.000000,327.0897,76500.2982,...,1127.687805,2790.0949,0.0,0.0,11465748,5447513,7086002.0,7966181.0,97668.308200,0.516333
6878,Zimbabwe,Africa,2019,1591.6049,171.0262,7.8322,0.0,73.000000,290.1893,76500.2982,...,2485.528399,2828.7215,0.0,0.0,11725970,5571525,7231989.0,8122618.0,98988.062800,0.985667
6879,Zimbabwe,Africa,2020,481.9027,48.4197,7.9733,0.0,73.000000,238.7639,76500.2982,...,1227.240253,2829.7457,0.0,0.0,11980005,5700460,7385220.0,8284447.0,96505.221850,0.189000

In [6]:
# Values missing per column
df01.isnull().sum()

Area                                 0
Continent                            0
Year                                 0
Savanna fires                        0
Forest fires                        62
Rice Cultivation                     0
Drained organic soils (CO2)          0
Pesticides Manufacturing             0
Food Transport                       0
Forestland                         493
Net Forest conversion              493
Food Household Consumption         472
Food Retail                          0
On-farm Electricity Use              0
Food Packaging                       0
Agrifood Systems Waste Disposal      0
Food Processing                      0
Fertilizers Manufacturing            0
Manure left on Pasture               0
Fires in organic soils               0
Fires in humid tropical forests    124
Rural population                     0
Urban population                     0
Total Population - Male              0
Total Population - Female            0
total_emission                       0
Average Temperature Â°C               0
dtype: int64